version: "3.8"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "10000:10000"

  proxy-client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
    - "20000:10000"

  http-upstream1:
    image: mendhak/http-https-echo
    environment:
    - HTTPS_PORT=9443
    ports:
    - "9443:9443"

  http-upstream2:
    image: mendhak/http-https-echo
    environment:
    - HTTP_PORT=8000
    ports:
    - "8000:8000"

  https-upstream3:
    image: mendhak/http-https-echo
    environment:
    - HTTP_PORT=9000
    ports:
    - "9000:9000"
